# Generated by Django 4.2.11 on 2024-09-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswer",
            name="subscription_status",
            field=models.CharField(default="Free", max_length=20),
        ),
    ]
