# Generated by Django 4.2.11 on 2024-09-09 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0003_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionanswer",
            name="created",
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
