# Generated by Django 4.2.11 on 2024-09-09 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0004_remove_questionanswer_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswer",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
