# Generated by Django 4.2.11 on 2024-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0005_questionanswer_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswer",
            name="session_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
